  - name: Adding user robosop
    ansible.builtin.user: 
      name: roboshop
  - name: "Creating /app directory"
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Downloading application code
    ansible.builtin.get_url: 
       url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
       dest: "/tmp/{{component}}.zip"
  - name: Extrarting application code
    ansible.builtin.unarchive:
      src: "/tmp/{{component}}.zip"
      dest: /app
      remote_src: yes
  