   - name: Installing golang 
     ansible.builtin.dnf: 
       name: golang
       state: latest

   - name: Installing dependencies
     ansible.builtin.shell: go mod init dispatch ; go get ; go build
     args:
      chdir: /app