    - name: Installing mysql
      ansible.builtin.dnf:
         name: mysql
         state: latest 
    - name: Loading schema
      ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/{{component}}.sql"
    - name: restarting "{{component}}"service
      ansible.builtin.service:
       name: "{{component}}"
       state: restarted
