    - name: Installing python 
      ansible.builtin.dnf: 
        name: 
          - python36
          - gcc
          - python3-devel
        state: latest
    - name: Installing dependencies
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
        chdir: /app