  - name: Copying "{{component}}".service file
    ansible.builtin.template:
      src: "{{component}}.service.j2"
      dest: "/etc/systemd/system/{{component}}.service"
  
  - name: Reloading systemd service
    ansible.builtin.systemd_service: 
       daemon_reload: true
  - name: "Enabling {{component}} service"
    ansible.builtin.service:
       name: "{{component}}"
       enabled: yes
  - name: "Starting {{component}} service"
    ansible.builtin.service:
      name: "{{component}}"
      state: started