- name: Preparing nodejs setup
  ansible.builtin.import_role:
     name: common
     tasks_from: app-setup
- name: Preparing nodejs setup
  ansible.builtin.import_role:
     name: common
     tasks_from: nodejs
- name: configuring service
  ansible.builtin.import_role:
     name: common
     tasks_from: service
- name: mongo client setup
  ansible.builtin.import_role:
     name: common
     tasks_from: mongoclient-setup